In [3]:
import numpy as np

#**🌟 Exercise 1 : Array Creation and Manipulation**

In [4]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#**🌟 Exercise 2 : Type Conversion and Array Operations**

In [6]:
x = np.array([3.14, 2.17, 0, 1, 2])
xx = np.int32(x)
xx

array([3, 2, 0, 1, 2], dtype=int32)

#**🌟 Exercise 3 : Working with Multi-Dimensional Arrays**

In [7]:
x = np.arange(1,10)
xx = np.reshape(x,(3,3))
xx


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#**Exercise 4 : Creating Multi-Dimensional Array with Random Numbers**

In [9]:
x = np.random.rand(4,5)
np.set_printoptions(precision=2)
x

array([[0.61, 0.43, 0.91, 0.92, 0.17],
       [0.51, 0.02, 0.37, 0.07, 0.8 ],
       [0.98, 0.64, 0.05, 0.56, 0.51],
       [0.08, 0.49, 0.07, 0.84, 0.47]])

#**Exercise 5 : Indexing Arrays**

In [11]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
x = array[1, :]
x

array([20, 21, 22, 23, 24])

#**Exercise 6 : Reversing elements**


In [12]:
array = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
x = array[::-1]
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#**🌟 Exercise 7 : Identity Matrix**

In [13]:
array = np.identity(4)
array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#**Exercise 8 : Simple Aggregate Funcs**

In [18]:
array = np.arange(6,30,3)

print(f'Sum: {np.sum(array)}, Average: {np.mean(array)}')

Sum: 132, Average: 16.5


#**🌟 Exercise 9 : Create Array and Change its Structure**

In [21]:
array = np.arange(1,21)
x = np.reshape(array,(4,5))
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

#**🌟 Exercise 9 : Create Array and Change its Structure**

In [23]:
array = np.arange(1,10)
x = array[array %2 != 0]
x

array([1, 3, 5, 7, 9])